In [20]:
import numpy as np

class Matrix:
    def __init__(self, data):
        """
        Initializes the matrix using a NumPy array.
        :param data: List of lists or NumPy array
        """
        self.data = np.array(data)

    def __str__(self):
        return str(self.data)

    def add(self, other):
        """Returns the sum of two matrices"""
        if self.data.shape != other.data.shape:
            raise ValueError('Matrix dimensions must match for addition.')
        return Matrix(self.data + other.data)

    def sub(self, other):
        """Returns the subtraction of two matrices"""
        if self.data.shape != other.data.shape:
            raise ValueError('Matrix dimensions must match for subtraction.')
        return Matrix(self.data - other.data)

    def multi(self, other):
        """Returns the multiplication of two matrices"""
        if self.data.shape[1] != other.data.shape[0]:
            raise ValueError('Invalid matrix dimensions for multiplication.')
        return Matrix(np.dot(self.data, other.data))

    def transpose(self):
        """Returns the transpose of the matrix"""
        return Matrix(self.data.T)


class SquareMatrix(Matrix):
    def __init__(self, data):
        """Ensures the matrix is square"""
        super().__init__(data)
        if self.data.shape[0] != self.data.shape[1]:
            raise ValueError("SquareMatrix must have equal number of rows and columns")

    def determinant(self):
        """Returns the determinant of the matrix."""
        return np.linalg.det(self.data)

    def is_symmetric(self):
        """Checks if the matrix is symmetric (A == A.T)."""
        return np.array_equal(self.data, self.data.T)


In [21]:
# Example Usage
A = SquareMatrix([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
B = SquareMatrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [5]:
print(A)

[[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]


In [6]:
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
# Matrix Operations
print("\nAddition of A and B:\n", A.add(B))
print("\nSubtraction of A and B:\n", A.sub(B))
print("\nMultiplication of A and B:\n", A.multi(B))
print("\nTranspose of A:\n", A.transpose())


Addition of A and B:
 [[ 3  1  3]
 [ 3  7  5]
 [ 7  7 11]]

Subtraction of A and B:
 [[ 1 -3 -3]
 [-5 -3 -7]
 [-7 -9 -7]]

Multiplication of A and B:
 [[-2 -1  0]
 [ 0  0  0]
 [10 11 12]]

Transpose of A:
 [[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]
